[httpserver]
listen=":7080"
tlsenable=false
tlscert="conf/server.crt"
tlskey="conf/server.key"
tlsclientauth=false
tlsclientsca="./conf/clintsca.crt"

[static]
dir="static"
urlpath="/static/"

[template]
dir="views"

[session]
# turn on/off session
enable=true
# maybe "file", "memory", "redis" 
store="memory"
cookiename="gmcsid"
ttl=3600

[session.file]
dir="{tmp}/.gmcsessions"
gctime=300
prefix=".gmcsession_"

[session.memory]
gctime=300

[session.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true

[cache]
# maybe "redis" 
[cache.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true