############################################################
# http server configuration 
############################################################
# 1.support of tls and optional client auth.
# 2.showerrorstack if on, when a panic error occurred
# call stack and error message will display on the browser 
############################################################
[httpserver]
listen=":7080"
tlsenable=false
tlscert="conf/server.crt"
tlskey="conf/server.key"
tlsclientauth=false
tlsclientsca="./conf/clintsca.crt"
printroute=true
showerrorstack=true

############################################################
# http server static files configuration 
############################################################
# 1.dir is a local filesystem path
# 2.urlpath is static dir url path
############################################################
[static]
dir="static"
urlpath="/static/"

#############################################################
# http server template configuration 
#############################################################
# 1.dir is a local template folder path
# 2.ext is extension of template file 
# 3.left and right delimiters to the specified strings, 
# to be used in subsequent calls to Parse
#############################################################
[template]
dir="views"
ext=".html"
delimiterleft="{{"
delimiterright="}}"

########################################################
# session configuration 
########################################################
# store can be "file", "memory", "redis" 
# {tmp} is a placeholder of system temp directory 
########################################################
[session]
# turn on/off session
enable=true
store="memory"
cookiename="gmcsid"
ttl=3600

[session.file]
dir="{tmp}/.gmcsessions"
gctime=300
prefix=".gmcsession_"

[session.memory]
gctime=300

[session.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true

########################################################
# cache configuration
########################################################
# redis supported
# support of mutiple redis server 
# notic: each config section must have an unique id 
########################################################
[cache]
default="redis"
[[cache.redis]]
debug=true
enable=true
id="default"
address="127.0.0.1:6379"
prefix=""
password=""
# seconds
timeout=10
dbnum=0
maxidle=10
maxactive=30
# seconds
idletimeout=300
# seconds
maxconnlifetime=3600
wait=true

########################################################
# database configuration
########################################################
# mysql,sqlite3 are both supported
# support of mutiple mysql server 
# support of mutiple sqlite3 database
# notic: each config section must have an unique id 
########################################################
[database]
[[database.mysql]]
enable=true
id="default"
host="127.0.0.1"
port="3306"
username="root"
password="admin"
database="test"
prefix=""
prefix_sql_holder="__PREFIX__"
charset="utf8"
collate="utf8_general_ci"
maxidle=30
maxconns=200
timeout=3000
readtimeout=5000
writetimeout=5000
maxlifetimeseconds=1800

[[database.mysql]]
enable=false
id="news"
host="127.0.0.1"
port="3306"
username="root"
password="admin"
database="test"
prefix=""
prefix_sql_holder="__PREFIX__"
charset="utf8"
collate="utf8_general_ci"
maxidle=30
maxconns=200
timeout=3000
readtimeout=5000
writetimeout=5000
maxlifetimeseconds=1800

[[database.sqlite3]]
enable=false
id="default"
database="test.db"
# if password is not empty , database will be encrypted.
password=""
prefix=""
prefix_sql_holder="__PREFIX__"
# syncmode 0:OFF, 1:NORMAL, 2:FULL, 3:EXTRA
syncmode=0
# openmode ro,rw,rwc,memory
openmode="rw"
# shared,private
cachemode="shared"