[httpserver]
listen=":7080"
tlsenable=false
tlscert="conf/server.crt"
tlskey="conf/server.key"
tlsclientauth=false
tlsclientsca="./conf/clintsca.crt"
printroute=true
showerrorstack=true

[static]
dir="static"
urlpath="/static/"

[template]
dir="views"

[session]
# turn on/off session
enable=true
# maybe "file", "memory", "redis" 
store="memory"
cookiename="gmcsid"
ttl=3600

[session.file]
# {tmp} is a placeholder of system temp directory 
dir="{tmp}/.gmcsessions"
gctime=300
prefix=".gmcsession_"

[session.memory]
gctime=300

[session.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true

[cache]
# maybe "redis" 
[cache.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true

[database]
[[database.mysql]]
enable=true
id="default"
host="127.0.0.1"
port="3306"
username="root"
password="admin"
database="test"
prefix=""
prefix_sql_holder="__PREFIX__"
charset="utf8"
collate="utf8_general_ci"
maxidle=30
maxconns=200
timeout=3000
readtimeout=5000
writetimeout=5000
maxlifetimeseconds=1800

[[database.mysql]]
enable=false
id="news"
host="127.0.0.1"
port="3306"
username="root"
password="admin"
database="test"
prefix=""
prefix_sql_holder="__PREFIX__"
charset="utf8"
collate="utf8_general_ci"
maxidle=30
maxconns=200
timeout=3000
readtimeout=5000
writetimeout=5000
maxlifetimeseconds=1800

[[database.sqlite3]]
enable=false
id="default"
database="test.db"
# if password is not empty , database will be encrypted.
password=""
prefix=""
prefix_sql_holder="__PREFIX__"
# syncmode 0:OFF, 1:NORMAL, 2:FULL, 3:EXTRA
syncmode=0
# openmode ro,rw,rwc,memory
openmode="rw"
# shared,private
cachemode="shared"