[session]
# turn on/off session
enable=true
# maybe "file", "memory", "redis" 
store="redis"
cookie_name="gmcsid"
ttl=3600

[session.file]
dir=""
gctime=300
prefix=".gmcsession_"

[session.memory]
gctime=300

[session.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true

[cache]
# maybe "redis" 
[cache.redis]
debug=false
address="127.0.0.1:6379"
prefix=""
password=""
timeout=10
dbnum=0
maxidle=10
maxactive=30
idletimeout=300
maxconnlifetime=3600
wait=true